-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--                                             // hydrogen // schema // reactive
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- | Reactive - Pillar 8 of the Hydrogen Schema.
-- |
-- | State and feedback atoms, molecules, and compounds for
-- | Frame.io-level hyper-responsive web interactions.
-- |
-- | This module re-exports all Reactive submodules.

module Hydrogen.Schema.Reactive
  ( module Hydrogen.Schema.Reactive.Flags
  , module Hydrogen.Schema.Reactive.Progress
  , module Hydrogen.Schema.Reactive.InteractiveState
  , module Hydrogen.Schema.Reactive.DataState
  , module Hydrogen.Schema.Reactive.ValidationState
  , module Hydrogen.Schema.Reactive.NetworkState
  , module Hydrogen.Schema.Reactive.SelectionState
  , module Hydrogen.Schema.Reactive.FocusManagement
  , module Hydrogen.Schema.Reactive.PresenceState
  , module Hydrogen.Schema.Reactive.MediaState
  , module Hydrogen.Schema.Reactive.DragState
  , module Hydrogen.Schema.Reactive.ScrollState
  , module Hydrogen.Schema.Reactive.Feedback
  , module Hydrogen.Schema.Reactive.ButtonSemantics
  , module Hydrogen.Schema.Reactive.Viewport
  , module Hydrogen.Schema.Reactive.ContainerQuery
  ) where

import Hydrogen.Schema.Reactive.Flags (ActiveFlag(ActiveFlag), AnimatingFlag(AnimatingFlag), BufferingFlag(BufferingFlag), BusyFlag(BusyFlag), CheckedFlag(CheckedFlag), CollapsedFlag(CollapsedFlag), DirtyFlag(DirtyFlag), DisabledFlag(DisabledFlag), DragOverFlag(DragOverFlag), DraggingFlag(DraggingFlag), DropTargetFlag(DropTargetFlag), EmptyFlag(EmptyFlag), EnabledFlag(EnabledFlag), EnteringFlag(EnteringFlag), ExitingFlag(ExitingFlag), ExpandedFlag(ExpandedFlag), FocusedFlag(FocusedFlag), FullscreenFlag(FullscreenFlag), HiddenFlag(HiddenFlag), HoveredFlag(HoveredFlag), IndeterminateFlag(IndeterminateFlag), InvalidFlag(InvalidFlag), LoadedFlag(LoadedFlag), LoadingFlag(LoadingFlag), MountedFlag(MountedFlag), MutedFlag(MutedFlag), OfflineFlag(OfflineFlag), OnlineFlag(OnlineFlag), OpenFlag(OpenFlag), PausedFlag(PausedFlag), PlayingFlag(PlayingFlag), PressedFlag(PressedFlag), PristineFlag(PristineFlag), ReadOnlyFlag(ReadOnlyFlag), ReconnectingFlag(ReconnectingFlag), RefreshingFlag(RefreshingFlag), RequiredFlag(RequiredFlag), SelectedFlag(SelectedFlag), StaleFlag(StaleFlag), TouchedFlag(TouchedFlag), UntouchedFlag(UntouchedFlag), ValidFlag(ValidFlag), VisibleFlag(VisibleFlag))
import Hydrogen.Schema.Reactive.Progress (BufferProgress, DownloadProgress, ProcessingProgress, Progress, RenderProgress, SeekProgress, StepProgress, TransferProgress, UploadProgress, bounds, bufferProgress, bytesLoaded, bytesTotal, currentStep, downloadProgress, isComplete, processingProgress, progress, renderProgress, seekProgress, stepPercent, stepProgress, toPercent, totalSteps, transferPercent, transferProgress, transferRate, unsafeProgress, unwrap, uploadProgress)
import Hydrogen.Schema.Reactive.InteractiveState (ActivationState(Inactive, Activating, Active, Deactivating), FocusState(FocusNone, FocusKeyboard, FocusPointer, FocusProgrammatic), InteractiveState, PointerDevice(Mouse, Touch, Pen, Unknown), PointerState(PointerIdle, PointerHover, PointerPressed, PointerDragging), activating, active, deactivating, defaultInteractive, focusKeyboard, focusNone, focusPointer, focusProgrammatic, hasFocus, inactive, interactiveState, isEngaged, isInteractable, isPointerDown, isPointerOver, pointerDevice, pointerHover, pointerIdle, pointerPressed, showFocusRing, toAriaAttributes, toLegacyCssClasses)
import Hydrogen.Schema.Reactive.DataState (DataMeta, FetchState(Idle, Fetching, Revalidating, Success, Failure), Freshness(Fresh, Stale, FreshnessUnknown), LoadingState, MutationState(MutationIdle, MutationPending, MutationOptimistic, MutationSuccess, MutationError, MutationRollingBack), RetryState, canRefresh, dataMeta, defaultMeta, hasLoadingError, isFetchError, isFetchIdle, isFetchSuccess, isFetching, isFresh, isLoading, isLoadingComplete, isMutating, isSettled, isStale, isUnknown, loadingComplete, loadingFailed, loadingIndeterminate, loadingPercent, loadingProgress, loadingState, loadingWithMessage, nextRetryDelay, noRetries, notLoading, retryState, shouldRetry, shouldShowLoading, shouldShowStale, updateProgress)
import Hydrogen.Schema.Reactive.ValidationState (FieldValidation, FormValidation, ModificationState(Pristine, Modified), TouchState(Untouched, Touched), ValidationMessage, ValidationResult(ValidationValid, ValidationInvalid, ValidationPending, ValidationSkipped), ValidationSeverity(SeverityError, SeverityWarning, SeverityInfo), allErrors, allWarnings, defaultFieldValidation, defaultFormValidation, dirtyFieldCount, errorMessage, fieldValidation, firstError, formValidation, hasMessages, infoMessage, invalidField, invalidFieldCount, isDirty, isFormSubmittable, isFormValid, isInvalidResult, isPendingResult, isPristine, isSeverityError, isSeverityInfo, isSeverityWarning, isTouched, isUntouched, isValidResult, pendingField, shouldShowError, shouldShowWarning, touchedFieldCount, validField, validationMessage, warningMessage)
import Hydrogen.Schema.Reactive.NetworkState (ConnectionQuality, ConnectionStatus(Online, Offline, Reconnecting), ConnectionType(Wifi, Cellular, Ethernet, Bluetooth, Wimax, None, UnknownType), Downlink(Downlink), EffectiveType(Slow2g, Ect2g, Ect3g, Ect4g), NetworkState, RoundTripTime(RoundTripTime), adaptiveImageQuality, canFetch, connectionQuality, defaultNetworkState, defaultQuality, downlinkBounds, downlinkMbps, is2g, is3g, is4g, isCellular, isEthernet, isFastDownlink, isHighLatency, isHighQuality, isLowLatency, isLowQuality, isOffline, isOnline, isReconnecting, isSlow2g, isSlowDownlink, isUnknownType, isWifi, networkState, offlineState, rttBounds, rttMs, shouldDeferLargeRequests, shouldReduceData, unwrapDownlink, unwrapRtt)
import Hydrogen.Schema.Reactive.SelectionState (HierarchicalStatus(FullySelected, PartiallySelected, NotSelected), MultiSelection, SelectionAnchor, SelectionMode(SelectionNone, SelectionSingle, SelectionMultiple, SelectionRange), SelectionRange, SelectionStatus(Selected, Unselected, Indeterminate), SingleSelection, anchorIndex, clearSingle, computeParentStatus, deselectAll, deselectIndex, emptyMultiSelection, expandRange, hasAnchor, hasSelection, isAllSelected, isFullySelected, isInRange, isIndeterminate, isMultipleMode, isNoneMode, isNoneSelected, isNotSelected, isPartiallySelected, isRangeMode, isSelected, isSingleMode, isSomeSelected, isUnselected, multiSelection, noAnchor, noSelection, rangeEnd, rangeSize, rangeStart, selectAll, selectIndex, selectRange, selectSingle, selectedIndex, selectedIndices, selectionAnchor, selectionCount, selectionRange, singleSelection, toggleIndex)
import Hydrogen.Schema.Reactive.FocusManagement (FocusOrigin(KeyboardOrigin, MouseOrigin, TouchOrigin, ProgrammaticOrigin), FocusRing, FocusRingStyle(OutlineRing, ShadowRing, BorderRing), FocusScope, FocusTrap, FocusTrapMode(HardTrap, SoftTrap, NoTrap), FocusVisibility(FocusVisible, FocusHidden, FocusAuto), RovingTabindex, accessibleFocusRing, defaultFocusRing, defaultScope, disabledTrap, focusRing, focusScope, focusTrap, hardTrap, highContrastFocusRing, initRoving, invertedFocusRing, isBorderRing, isFocusHidden, isFocusVisible, isHardTrap, isKeyboardOrigin, isMouseOrigin, isNoTrap, isOutlineRing, isProgrammaticOrigin, isRovingFocused, isScopeActive, isShadowRing, isSoftTrap, isTouchOrigin, isTrapActive, modalScope, noFocusRing, rovingFocusIndex, rovingMoveFirst, rovingMoveLast, rovingMoveNext, rovingMovePrev, rovingTabindex, scopeFocusedId, scopeWithTrap, shouldReturnFocus, shouldShowRing, softTrap, withRingColor, withRingOffset, withRingWidth, withTwoRing)
import Hydrogen.Schema.Reactive.PresenceState (AnimationDirection(Forward, Backward, NoDirection), MountStatus(Unmounted, Mounting, Mounted, Unmounting), PresenceConfig, PresenceGroup, PresencePhase(PhaseEntering, PhaseEntered, PhaseExiting, PhaseExited), PresenceState, addToGroup, animationProgress, animationRemainingTime, cancelAnimation, completeEnter, completeExit, defaultPresenceConfig, emptyGroup, enteredPresence, enteringPresence, exitedPresence, exitingPresence, groupPendingExits, initialPresence, instantConfig, isAnimating, isBackward, isEntered, isEntering, isExited, isExiting, isForward, isGroupAnimating, isMounted, isMounting, isNoDirection, isPresent, isUnmounted, isUnmounting, presenceConfig, presenceGroup, presenceState, removeFromGroup, shouldAnimate, shouldRender, startEnter, startExit, withEnterDuration, withExitDuration)
import Hydrogen.Schema.Reactive.MediaState (BufferedRange, Duration(Duration), MediaProgress, MediaState, NetworkLoadState(NetworkEmpty, NetworkIdle, NetworkLoading, NetworkNoSource), PlaybackRate(PlaybackRate), PlaybackStatus(Playing, Paused, Stopped, Buffering, Seeking, Ended, Error), ReadyState(HaveNothing, HaveMetadata, HaveCurrentData, HaveFutureData, HaveEnoughData), TimePosition(TimePosition), VolumeLevel(VolumeLevel), bufferedPercent, bufferedRange, canPlay, canPlayThrough, canSeek, doubleSpeed, duration, endedState, formattedCurrentTime, formattedDuration, fullVolume, halfSpeed, halfVolume, hasDuration, hasError, initialMediaState, initialProgress, isAudible, isBuffering, isEnded, isFastForward, isHaveCurrentData, isHaveEnoughData, isHaveFutureData, isHaveMetadata, isHaveNothing, isMuted, isNetworkEmpty, isNetworkIdle, isNetworkLoading, isNetworkNoSource, isNormalSpeed, isPaused, isPlaying, isSeeking, isSlowMotion, isStopped, mediaProgress, mediaState, muted, normalSpeed, pause, pausedState, play, playbackRate, playbackRateBounds, playingState, progressPercent, rangeEndTime, rangeLength, rangeStartTime, remainingTime, seek, setPlaybackRate, setVolume, shouldShowBuffering, shouldShowControls, startPosition, stop, timePosition, timePositionBounds, toggleMute, unknownDuration, unwrapDuration, unwrapRate, unwrapTime, unwrapVolume, volumeLevel, volumeLevelBounds)
import Hydrogen.Schema.Reactive.DragState (DragPosition, DragPreview, DragSource, DragState, DragStatus(DragIdle, Dragging, DraggedOver, Dropping), DragType(FileDrag, ElementDrag, TextDrag, ExternalDrag), DropEffect(DropCopy, DropMove, DropLink, DropNone), DropTarget, DropZoneFeedback(DropZoneAccepting, DropZoneRejecting, DropZoneNeutral), acceptedTypes, activeDragState, cancelDrag, currentPosition, customPreview, defaultPreview, deltaX, deltaY, dragPosition, dragPreview, dragSource, dragSourceData, dragSourceId, dragState, drop, dropTarget, dropTargetId, enterDropZone, ghostPreview, hasValidDropTarget, idleDragState, isAccepting, isCopy, isDragActive, isDragIdle, isDragSourceActive, isDraggedOver, isDragging, isDropNone, isDropping, isElementDrag, isExternalDrag, isFileDrag, isLink, isMove, isNeutral, isRejecting, isTargetActive, isTextDrag, isValidTarget, leaveDropZone, noDragSource, noDropTarget, originPosition, previewOffset, previewPosition, shouldShowPreview, startDrag, totalDistance, updateDragPosition)
import Hydrogen.Schema.Reactive.ScrollState (OverflowBehavior(OverflowAuto, OverflowScroll, OverflowHidden, OverflowVisible), OverscrollBehavior(OverscrollAuto, OverscrollContain, OverscrollNone), ScrollBehavior(SmoothScroll, InstantScroll, AutoScroll), ScrollBounds, ScrollDirection(ScrollUp, ScrollDown, ScrollLeft, ScrollRight, ScrollIdle), ScrollPosition, ScrollProgress, ScrollSnapAlign(SnapAlignStart, SnapAlignCenter, SnapAlignEnd), ScrollSnapType(SnapMandatory, SnapProximity, SnapNone), ScrollState, ScrollVelocity, canScrollX, canScrollY, distanceToEnd, initialScrollState, isAtEnd, isAtStart, isAuto, isFastScroll, isHorizontalScroll, isInstant, isNearEnd, isOverflowAuto, isOverflowHidden, isOverflowScroll, isOverflowVisible, isOverscrollAuto, isOverscrollContain, isOverscrollNone, isScrollIdle, isScrolling, isScrollingDown, isScrollingLeft, isScrollingRight, isScrollingUp, isSmooth, isSnapCenter, isSnapEnd, isSnapMandatory, isSnapNone, isSnapProximity, isSnapStart, isVerticalScroll, maxScrollX, maxScrollY, noVelocity, originScroll, progressX, progressY, scrollBounds, scrollLeft, scrollPercentage, scrollPosition, scrollProgress, scrollState, scrollTop, scrollVelocity, scrollX, scrollY, setScrollBehavior, shouldLoadMore, shouldShowScrollbar, updateScrollPosition, updateScrollVelocity, velocityX, velocityY)
import Hydrogen.Schema.Reactive.Feedback (Alert, Banner, Dialog, DialogType(ConfirmDialog, AlertDialogType, PromptDialog), DismissalMethod(AutoDismiss, ManualDismiss, ActionDismiss, SwipeDismiss), Drawer, DrawerPosition(DrawerLeft, DrawerRight, DrawerTop, DrawerBottom), FeedbackAction, FeedbackDuration(DurationShort, DurationMedium, DurationLong, DurationPersistent), FeedbackPosition(TopLeft, TopCenter, TopRight, BottomLeft, BottomCenter, BottomRight), FeedbackSeverity(FeedbackSuccess, FeedbackInfo, FeedbackWarning, FeedbackError, FeedbackNeutral), FeedbackType(ToastType, SnackbarType, BannerType, AlertType, DialogType'), NotificationQueue, Popover, PopoverTrigger(PopoverClick, PopoverHover, PopoverFocus, PopoverManual), Sheet, SheetSnapPoint(SheetMinimized, SheetPartial, SheetExpanded, SheetCustom), Snackbar, Toast, Tooltip, TooltipPlacement(TooltipTop, TooltipTopStart, TooltipTopEnd, TooltipBottom, TooltipBottomStart, TooltipBottomEnd, TooltipLeft, TooltipLeftStart, TooltipLeftEnd, TooltipRight, TooltipRightStart, TooltipRightEnd), actionLabel, alert, alertDialog, alertWithActions, banner, closeDrawer, closePopover, closeSheet, confirmDialog, currentNotification, dequeue, destructiveDialog, dialog, dismissAction, drawer, durationMs, emptyQueue, enqueue, errorBanner, errorToast, feedbackAction, hasAction, infoBanner, infoToast, inlineAlert, interactiveTooltip, isActionDismiss, isAlert, isAlertDialog, isAutoDismiss, isBanner, isBlocking, isBottomCenter, isBottomLeft, isBottomRight, isConfirmDialog, isDialog, isDrawerOpen, isFeedbackError, isFeedbackInfo, isFeedbackNeutral, isFeedbackSuccess, isFeedbackWarning, isLong, isManualDismiss, isMedium, isPersistent, isPopoverOpen, isPromptDialog, isSheetOpen, isShort, isSnackbar, isSwipeDismiss, isToast, isTopCenter, isTopLeft, isTopRight, multiDetentSheet, navigationDrawer, openDrawer, openPopover, openSheet, popover, popoverWithTitle, queueLength, retryAction, sheet, shouldAutoDismiss, sidePanelDrawer, simpleTooltip, snackbar, snackbarWithAction, snackbarWithUndo, snapSheet, standardSheet, successToast, toast, toggleDrawer, tooltip, undoAction, warningBanner, warningToast)
import Hydrogen.Schema.Reactive.ButtonSemantics (ButtonIdentity, ButtonPurpose(ActionButton, FormSubmit, FormReset, NavigationButton, MediaControl, ToggleControl, MenuTrigger, DialogTrigger, DisclosureTrigger, DangerAction, IconAction, FloatingAction), MediaAction(PlayAction, PauseAction, StopAction, FastForwardAction, RewindAction, SkipForwardAction, SkipBackwardAction, NextTrackAction, PreviousTrackAction, MuteAction, UnmuteAction, VolumeUpAction, VolumeDownAction, FullscreenAction, ExitFullscreenAction, PictureInPictureAction, ClosedCaptionsAction, SettingsAction, RecordAction, LiveAction), PopupType(MenuPopup, ListboxPopup, TreePopup, GridPopup, DialogPopup), ToggleState(Pressed, Unpressed, Mixed), actionButton, ariaRole, buttonId, buttonIdString, buttonIdentity, closedCaptionsAction, dangerAction, dialogPopup, dialogTrigger, disclosureTrigger, exitFullscreenAction, fastForwardAction, floatingAction, formReset, formSubmit, fullscreenAction, gridPopup, htmlType, iconAction, isPressed, listboxPopup, liveAction, mediaActionLabel, mediaControl, menuPopup, menuTrigger, mixed, muteAction, navigationButton, nextTrackAction, pauseAction, pictureInPictureAction, playAction, popupTypeToAria, pressed, previousTrackAction, recordAction, requiresAriaLabel, rewindAction, settingsAction, skipBackwardAction, skipForwardAction, stopAction, toggleControl, toggleStateToAria, treePopup, unmuteAction, unpressed, volumeDownAction, volumeUpAction)
import Hydrogen.Schema.Reactive.Viewport (Breakpoint(Xs, Sm, Md, Lg, Xl, Xxl), DeviceClass(Phone, Tablet, Desktop, LargeDesktop), Orientation(Portrait, Landscape, Square), ResponsiveSpec, ResponsiveValue, Viewport, ViewportControl(Zoom, Pan, Scroll, Fullscreen, Refresh, Close), ViewportControls, ViewportId, ViewportState, ZoomLevel(ZoomLevel), addControl, allBreakpoints, breakpointClass, breakpointFromDimensions, breakpointFromWidth, breakpointMax, breakpointMin, breakpointRange, containerQueryCss, defaultControls, deviceClassFromBreakpoint, deviceClassFromWidth, getBreakpoint, getDeviceClass, getDimensions, getHeight, getId, getOrientation, getWidth, hasControl, initialState, isAtLeast, isAtMost, isBetween, mediaQuery, mediaQueryMax, mediaQueryRange, orientationFromAspectRatio, orientationFromDimensions, removeControl, resolve, resolveFor, responsive, static, unwrapViewportId, unwrapZoom, viewport, viewportId, viewportIdFromString, viewportIdToString, viewportNamespace, viewportWithId, withFullscreen, withScroll, withZoom, zoom100, zoom200, zoom50, zoomFill, zoomFit, zoomLevel)
import Hydrogen.Schema.Reactive.ContainerQuery (Container, ContainerQuery, ContainerResponsive, ContainerResponsiveSpec, ContainerType(InlineSize, BlockSize, Size, Normal), QueryCondition, QueryContainer, aspectRatio, aspectRatioMax, aspectRatioMin, breakpointFromContainerWidth, containerName, containerNameLegacyCss, containerQuery, containerQueryNamed, containerResponsive, containerStatic, containerStylesLegacyCss, containerType, containerTypeLegacyCss, containerTypeToLegacyCss, heightRange, isAtLeastBreakpoint, isBelowBreakpoint, isWithinBreakpoint, maxHeight, maxWidth, minHeight, minWidth, orientation, queryCondition, queryContainer, queryContainerNamed, queryToLegacyCss, resolveAtWidth, widthRange)
