-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--                                             // hydrogen // schema // reactive
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- | Reactive - Pillar 8 of the Hydrogen Schema.
-- |
-- | State and feedback atoms, molecules, and compounds for
-- | Frame.io-level hyper-responsive web interactions.
-- |
-- | This module re-exports all Reactive submodules.

module Hydrogen.Schema.Reactive
  ( module Hydrogen.Schema.Reactive.Flags
  , module Hydrogen.Schema.Reactive.Progress
  , module Hydrogen.Schema.Reactive.InteractiveState
  , module Hydrogen.Schema.Reactive.DataState
  , module Hydrogen.Schema.Reactive.ValidationState
  , module Hydrogen.Schema.Reactive.NetworkState
  , module Hydrogen.Schema.Reactive.SelectionState
  , module Hydrogen.Schema.Reactive.FocusManagement
  , module Hydrogen.Schema.Reactive.PresenceState
  , module Hydrogen.Schema.Reactive.MediaState
  , module Hydrogen.Schema.Reactive.DragState
  , module Hydrogen.Schema.Reactive.ScrollState
  , module Hydrogen.Schema.Reactive.Feedback
  , module Hydrogen.Schema.Reactive.ButtonSemantics
  , module Hydrogen.Schema.Reactive.Viewport
  , module Hydrogen.Schema.Reactive.ContainerQuery
  ) where

import Hydrogen.Schema.Reactive.Flags (ActiveFlag(..), AnimatingFlag(..), BufferingFlag(..), BusyFlag(..), CheckedFlag(..), CollapsedFlag(..), DirtyFlag(..), DisabledFlag(..), DragOverFlag(..), DraggingFlag(..), DropTargetFlag(..), EmptyFlag(..), EnabledFlag(..), EnteringFlag(..), ExitingFlag(..), ExpandedFlag(..), FocusedFlag(..), FullscreenFlag(..), HiddenFlag(..), HoveredFlag(..), IndeterminateFlag(..), InvalidFlag(..), LoadedFlag(..), LoadingFlag(..), MountedFlag(..), MutedFlag(..), OfflineFlag(..), OnlineFlag(..), OpenFlag(..), PausedFlag(..), PlayingFlag(..), PressedFlag(..), PristineFlag(..), ReadOnlyFlag(..), ReconnectingFlag(..), RefreshingFlag(..), RequiredFlag(..), SelectedFlag(..), StaleFlag(..), TouchedFlag(..), UntouchedFlag(..), ValidFlag(..), VisibleFlag(..))
import Hydrogen.Schema.Reactive.Progress (BufferProgress, DownloadProgress, ProcessingProgress, Progress, RenderProgress, SeekProgress, StepProgress, TransferProgress, UploadProgress, bounds, bufferProgress, bytesLoaded, bytesTotal, currentStep, downloadProgress, isComplete, processingProgress, progress, renderProgress, seekProgress, stepPercent, stepProgress, toPercent, totalSteps, transferPercent, transferProgress, transferRate, unsafeProgress, unwrap, uploadProgress)
import Hydrogen.Schema.Reactive.InteractiveState (ActivationState(..), FocusState(..), InteractiveState, PointerDevice(..), PointerState(..), activating, active, deactivating, defaultInteractive, focusKeyboard, focusNone, focusPointer, focusProgrammatic, hasFocus, inactive, interactiveState, isEngaged, isInteractable, isPointerDown, isPointerOver, pointerDevice, pointerHover, pointerIdle, pointerPressed, showFocusRing, toAriaAttributes, toLegacyCssClasses)
import Hydrogen.Schema.Reactive.DataState (DataMeta, FetchState(..), Freshness(..), LoadingState, MutationState(..), RetryState, canRefresh, dataMeta, defaultMeta, hasLoadingError, isFetchError, isFetchIdle, isFetchSuccess, isFetching, isFresh, isLoading, isLoadingComplete, isMutating, isSettled, isStale, isUnknown, loadingComplete, loadingFailed, loadingIndeterminate, loadingPercent, loadingProgress, loadingState, loadingWithMessage, nextRetryDelay, noRetries, notLoading, retryState, shouldRetry, shouldShowLoading, shouldShowStale, updateProgress)
import Hydrogen.Schema.Reactive.ValidationState (FieldValidation, FormValidation, ModificationState(..), TouchState(..), ValidationMessage, ValidationResult(..), ValidationSeverity(..), allErrors, allWarnings, defaultFieldValidation, defaultFormValidation, dirtyFieldCount, errorMessage, fieldValidation, firstError, formValidation, hasMessages, infoMessage, invalidField, invalidFieldCount, isDirty, isFormSubmittable, isFormValid, isInvalidResult, isPendingResult, isPristine, isSeverityError, isSeverityInfo, isSeverityWarning, isTouched, isUntouched, isValidResult, pendingField, shouldShowError, shouldShowWarning, touchedFieldCount, validField, validationMessage, warningMessage)
import Hydrogen.Schema.Reactive.NetworkState (ConnectionQuality, ConnectionStatus(..), ConnectionType(..), Downlink(..), EffectiveType(..), NetworkState, RoundTripTime(..), adaptiveImageQuality, canFetch, connectionQuality, defaultNetworkState, defaultQuality, downlinkBounds, downlinkMbps, is2g, is3g, is4g, isCellular, isEthernet, isFastDownlink, isHighLatency, isHighQuality, isLowLatency, isLowQuality, isOffline, isOnline, isReconnecting, isSlow2g, isSlowDownlink, isUnknownType, isWifi, networkState, offlineState, rttBounds, rttMs, shouldDeferLargeRequests, shouldReduceData, unwrapDownlink, unwrapRtt)
import Hydrogen.Schema.Reactive.SelectionState (HierarchicalStatus(..), MultiSelection, SelectionAnchor, SelectionMode(..), SelectionRange, SelectionStatus(..), SingleSelection, anchorIndex, clearSingle, computeParentStatus, deselectAll, deselectIndex, emptyMultiSelection, expandRange, hasAnchor, hasSelection, isAllSelected, isFullySelected, isInRange, isIndeterminate, isMultipleMode, isNoneMode, isNoneSelected, isNotSelected, isPartiallySelected, isRangeMode, isSelected, isSingleMode, isSomeSelected, isUnselected, multiSelection, noAnchor, noSelection, rangeEnd, rangeSize, rangeStart, selectAll, selectIndex, selectRange, selectSingle, selectedIndex, selectedIndices, selectionAnchor, selectionCount, selectionRange, singleSelection, toggleIndex)
import Hydrogen.Schema.Reactive.FocusManagement (FocusOrigin(..), FocusRing, FocusRingStyle(..), FocusScope, FocusTrap, FocusTrapMode(..), FocusVisibility(..), RovingTabindex, accessibleFocusRing, defaultFocusRing, defaultScope, disabledTrap, focusRing, focusScope, focusTrap, hardTrap, highContrastFocusRing, initRoving, invertedFocusRing, isBorderRing, isFocusHidden, isFocusVisible, isHardTrap, isKeyboardOrigin, isMouseOrigin, isNoTrap, isOutlineRing, isProgrammaticOrigin, isRovingFocused, isScopeActive, isShadowRing, isSoftTrap, isTouchOrigin, isTrapActive, modalScope, noFocusRing, rovingFocusIndex, rovingMoveFirst, rovingMoveLast, rovingMoveNext, rovingMovePrev, rovingTabindex, scopeFocusedId, scopeWithTrap, shouldReturnFocus, shouldShowRing, softTrap, withRingColor, withRingOffset, withRingWidth, withTwoRing)
import Hydrogen.Schema.Reactive.PresenceState (AnimationDirection(..), MountStatus(..), PresenceConfig, PresenceGroup, PresencePhase(..), PresenceState, addToGroup, animationProgress, animationRemainingTime, cancelAnimation, completeEnter, completeExit, defaultPresenceConfig, emptyGroup, enteredPresence, enteringPresence, exitedPresence, exitingPresence, groupPendingExits, initialPresence, instantConfig, isAnimating, isBackward, isEntered, isEntering, isExited, isExiting, isForward, isGroupAnimating, isMounted, isMounting, isNoDirection, isPresent, isUnmounted, isUnmounting, presenceConfig, presenceGroup, presenceState, removeFromGroup, shouldAnimate, shouldRender, startEnter, startExit, withEnterDuration, withExitDuration)
import Hydrogen.Schema.Reactive.MediaState (BufferedRange, Duration(..), MediaProgress, MediaState, NetworkLoadState(..), PlaybackRate(..), PlaybackStatus(..), ReadyState(..), TimePosition(..), VolumeLevel(..), bufferedPercent, bufferedRange, canPlay, canPlayThrough, canSeek, doubleSpeed, duration, endedState, formattedCurrentTime, formattedDuration, fullVolume, halfSpeed, halfVolume, hasDuration, hasError, initialMediaState, initialProgress, isAudible, isBuffering, isEnded, isFastForward, isHaveCurrentData, isHaveEnoughData, isHaveFutureData, isHaveMetadata, isHaveNothing, isMuted, isNetworkEmpty, isNetworkIdle, isNetworkLoading, isNetworkNoSource, isNormalSpeed, isPaused, isPlaying, isSeeking, isSlowMotion, isStopped, mediaProgress, mediaState, muted, normalSpeed, pause, pausedState, play, playbackRate, playbackRateBounds, playingState, progressPercent, rangeEndTime, rangeLength, rangeStartTime, remainingTime, seek, setPlaybackRate, setVolume, shouldShowBuffering, shouldShowControls, startPosition, stop, timePosition, timePositionBounds, toggleMute, unknownDuration, unwrapDuration, unwrapRate, unwrapTime, unwrapVolume, volumeLevel, volumeLevelBounds)
import Hydrogen.Schema.Reactive.DragState (DragPosition, DragPreview, DragSource, DragState, DragStatus(..), DragType(..), DropEffect(..), DropTarget, DropZoneFeedback(..), acceptedTypes, activeDragState, cancelDrag, currentPosition, customPreview, defaultPreview, deltaX, deltaY, dragPosition, dragPreview, dragSource, dragSourceData, dragSourceId, dragState, drop, dropTarget, dropTargetId, enterDropZone, ghostPreview, hasValidDropTarget, idleDragState, isAccepting, isCopy, isDragActive, isDragIdle, isDragSourceActive, isDraggedOver, isDragging, isDropNone, isDropping, isElementDrag, isExternalDrag, isFileDrag, isLink, isMove, isNeutral, isRejecting, isTargetActive, isTextDrag, isValidTarget, leaveDropZone, noDragSource, noDropTarget, originPosition, previewOffset, previewPosition, shouldShowPreview, startDrag, totalDistance, updateDragPosition)
import Hydrogen.Schema.Reactive.ScrollState (OverflowBehavior(..), OverscrollBehavior(..), ScrollBehavior(..), ScrollBounds, ScrollDirection(..), ScrollPosition, ScrollProgress, ScrollSnapAlign(..), ScrollSnapType(..), ScrollState, ScrollVelocity, canScrollX, canScrollY, distanceToEnd, initialScrollState, isAtEnd, isAtStart, isAuto, isFastScroll, isHorizontalScroll, isInstant, isNearEnd, isOverflowAuto, isOverflowHidden, isOverflowScroll, isOverflowVisible, isOverscrollAuto, isOverscrollContain, isOverscrollNone, isScrollIdle, isScrolling, isScrollingDown, isScrollingLeft, isScrollingRight, isScrollingUp, isSmooth, isSnapCenter, isSnapEnd, isSnapMandatory, isSnapNone, isSnapProximity, isSnapStart, isVerticalScroll, maxScrollX, maxScrollY, noVelocity, originScroll, progressX, progressY, scrollBounds, scrollLeft, scrollPercentage, scrollPosition, scrollProgress, scrollState, scrollTop, scrollVelocity, scrollX, scrollY, setScrollBehavior, shouldLoadMore, shouldShowScrollbar, updateScrollPosition, updateScrollVelocity, velocityX, velocityY)
import Hydrogen.Schema.Reactive.Feedback (Alert, Banner, Dialog, DialogType(..), DismissalMethod(..), Drawer, DrawerPosition(..), FeedbackAction, FeedbackDuration(..), FeedbackPosition(..), FeedbackSeverity(..), FeedbackType(..), NotificationQueue, Popover, PopoverTrigger(..), Sheet, SheetSnapPoint(..), Snackbar, Toast, Tooltip, TooltipPlacement(..), actionLabel, alert, alertDialog, alertWithActions, banner, closeDrawer, closePopover, closeSheet, confirmDialog, currentNotification, dequeue, destructiveDialog, dialog, dismissAction, drawer, durationMs, emptyQueue, enqueue, errorBanner, errorToast, feedbackAction, hasAction, infoBanner, infoToast, inlineAlert, interactiveTooltip, isActionDismiss, isAlert, isAlertDialog, isAutoDismiss, isBanner, isBlocking, isBottomCenter, isBottomLeft, isBottomRight, isConfirmDialog, isDialog, isDrawerOpen, isFeedbackError, isFeedbackInfo, isFeedbackNeutral, isFeedbackSuccess, isFeedbackWarning, isLong, isManualDismiss, isMedium, isPersistent, isPopoverOpen, isPromptDialog, isSheetOpen, isShort, isSnackbar, isSwipeDismiss, isToast, isTopCenter, isTopLeft, isTopRight, multiDetentSheet, navigationDrawer, openDrawer, openPopover, openSheet, popover, popoverWithTitle, queueLength, retryAction, sheet, shouldAutoDismiss, sidePanelDrawer, simpleTooltip, snackbar, snackbarWithAction, snackbarWithUndo, snapSheet, standardSheet, successToast, toast, toggleDrawer, tooltip, undoAction, warningBanner, warningToast)
import Hydrogen.Schema.Reactive.ButtonSemantics (ButtonIdentity, ButtonPurpose(..), MediaAction(..), PopupType(..), ToggleState(..), actionButton, ariaRole, buttonId, buttonIdString, buttonIdentity, closedCaptionsAction, dangerAction, dialogPopup, dialogTrigger, disclosureTrigger, exitFullscreenAction, fastForwardAction, floatingAction, formReset, formSubmit, fullscreenAction, gridPopup, htmlType, iconAction, isPressed, listboxPopup, liveAction, mediaActionLabel, mediaControl, menuPopup, menuTrigger, mixed, muteAction, navigationButton, nextTrackAction, pauseAction, pictureInPictureAction, playAction, popupTypeToAria, pressed, previousTrackAction, recordAction, requiresAriaLabel, rewindAction, settingsAction, skipBackwardAction, skipForwardAction, stopAction, toggleControl, toggleStateToAria, treePopup, unmuteAction, unpressed, volumeDownAction, volumeUpAction)
import Hydrogen.Schema.Reactive.Viewport (Breakpoint(..), DeviceClass(..), Orientation(..), ResponsiveSpec, ResponsiveValue, Viewport, ViewportControl(..), ViewportControls, ViewportId, ViewportState, ZoomLevel(..), addControl, allBreakpoints, breakpointClass, breakpointFromDimensions, breakpointFromWidth, breakpointMax, breakpointMin, breakpointRange, containerQueryCss, defaultControls, deviceClassFromBreakpoint, deviceClassFromWidth, getBreakpoint, getDeviceClass, getDimensions, getHeight, getId, getOrientation, getWidth, hasControl, initialState, isAtLeast, isAtMost, isBetween, mediaQuery, mediaQueryMax, mediaQueryRange, orientationFromAspectRatio, orientationFromDimensions, removeControl, resolve, resolveFor, responsive, static, unwrapViewportId, unwrapZoom, viewport, viewportId, viewportIdFromString, viewportIdToString, viewportNamespace, viewportWithId, withFullscreen, withScroll, withZoom, zoom100, zoom200, zoom50, zoomFill, zoomFit, zoomLevel)
import Hydrogen.Schema.Reactive.ContainerQuery (Container, ContainerQuery, ContainerResponsive, ContainerResponsiveSpec, ContainerType(..), QueryCondition, QueryContainer, aspectRatio, aspectRatioMax, aspectRatioMin, breakpointFromContainerWidth, containerName, containerNameLegacyCss, containerQuery, containerQueryNamed, containerResponsive, containerStatic, containerStylesLegacyCss, containerType, containerTypeLegacyCss, containerTypeToLegacyCss, heightRange, isAtLeastBreakpoint, isBelowBreakpoint, isWithinBreakpoint, maxHeight, maxWidth, minHeight, minWidth, orientation, queryCondition, queryContainer, queryContainerNamed, queryToLegacyCss, resolveAtWidth, widthRange)
