{- |
-- ===========================================================================
--                               // foundry // extract // hydrogen
-- ===========================================================================

Module      : Foundry.Extract.Hydrogen
Description : Generate PureScript Hydrogen code from extracted components
Copyright   : (c) Straylight Software, 2026
License     : BSD-3-Clause

Generates PureScript source files for Hydrogen atoms, molecules, and compounds.

== Output Structure

Generated files follow atomic design:

@
  Brand/
    Atoms/
      Colors.purs       -- Color constants
      Typography.purs   -- Font stacks
      Spacing.purs      -- Spacing scale
    Molecules/
      Button.purs       -- Button component
      Input.purs        -- Input component
    Compounds/
      Card.purs         -- Card layout
      Hero.purs         -- Hero section
    Theme.purs          -- Combined theme
@

== Dependencies

Requires: Foundry.Extract.Component
Required by: Demo pipeline, CLI

-- ===========================================================================
-}
module Foundry.Extract.Hydrogen
  ( -- * Code Generation
    generateColorAtoms
  , generateFontAtoms
  , generateSpacingAtoms
  , generateButtonMolecule
  , generateHeroCompound
  , generateTheme

    -- * Full Generation
  , GeneratedCode (..)
  , generateAll
  ) where

import Data.Text (Text)
import Data.Text qualified as T
import Data.UUID qualified as UUID
import Data.Vector (Vector)
import Data.Vector qualified as V

import Foundry.Extract.Component
  ( ButtonMoleculeRec (..)
  , CardCompoundRec (..)
  , ColorAtomRec (..)
  , ExtractedRegistry (..)
  , FontAtomRec (..)
  , HeroCompoundRec (..)
  , SpacingAtomRec (..)
  )

-- ===========================================================================
-- Generated Code Bundle
-- ===========================================================================

-- | All generated PureScript code
data GeneratedCode = GeneratedCode
  { gcColors     :: !Text
  , gcTypography :: !Text
  , gcSpacing    :: !Text
  , gcButtons    :: !Text
  , gcHero       :: !Text
  , gcTheme      :: !Text
  }
  deriving stock (Eq, Show)

-- ===========================================================================
-- Color Atoms
-- ===========================================================================

-- | Generate PureScript module for color atoms
generateColorAtoms :: Text -> Vector ColorAtomRec -> Text
generateColorAtoms domain colors = T.unlines $
  [ "-- | Color atoms for " <> domain
  , "-- | Generated by Foundry Brand Ingestion Engine"
  , "-- | DO NOT EDIT - regenerate from brand source"
  , "module Brand.Atoms.Colors where"
  , ""
  , "import Prelude"
  , ""
  , "-- ============================================================"
  , "-- COLOR PALETTE"
  , "-- ============================================================"
  , ""
  ] ++ V.toList (V.map colorToPS colors)

-- | Convert color atom to PureScript constant
colorToPS :: ColorAtomRec -> Text
colorToPS c = T.unlines
  [ "-- | " <> carName c <> " (" <> carRole c <> ")"
  , "-- | UUID5: " <> UUID.toText (carId c)
  , sanitizeName (carName c) <> " :: String"
  , sanitizeName (carName c) <> " = \"" <> carHex c <> "\""
  , ""
  ]

-- ===========================================================================
-- Font Atoms
-- ===========================================================================

-- | Generate PureScript module for font atoms
generateFontAtoms :: Text -> Vector FontAtomRec -> Text
generateFontAtoms domain fonts = T.unlines $
  [ "-- | Typography atoms for " <> domain
  , "-- | Generated by Foundry Brand Ingestion Engine"
  , "module Brand.Atoms.Typography where"
  , ""
  , "import Prelude"
  , ""
  , "-- ============================================================"
  , "-- FONT FAMILIES"
  , "-- ============================================================"
  , ""
  ] ++ V.toList (V.map fontToPS fonts)

-- | Convert font atom to PureScript
fontToPS :: FontAtomRec -> Text
fontToPS f = T.unlines
  [ "-- | " <> farFamily f <> " (" <> farRole f <> ")"
  , "-- | UUID5: " <> UUID.toText (farId f)
  , "font" <> T.toTitle (farRole f) <> " :: String"
  , "font" <> T.toTitle (farRole f) <> " = \"" <> farFamily f <> ", " <> fallback (farRole f) <> "\""
  , ""
  ]
  where
    fallback role
      | role == "mono" = "ui-monospace, monospace"
      | role == "heading" = "ui-sans-serif, system-ui, sans-serif"
      | otherwise = "ui-sans-serif, system-ui, sans-serif"

-- ===========================================================================
-- Spacing Atoms
-- ===========================================================================

-- | Generate PureScript module for spacing atoms
generateSpacingAtoms :: Text -> Vector SpacingAtomRec -> Text
generateSpacingAtoms domain spacing = T.unlines $
  [ "-- | Spacing atoms for " <> domain
  , "-- | Generated by Foundry Brand Ingestion Engine"
  , "module Brand.Atoms.Spacing where"
  , ""
  , "import Prelude"
  , ""
  , "-- ============================================================"
  , "-- SPACING SCALE"
  , "-- ============================================================"
  , ""
  ] ++ V.toList (V.map spacingToPS spacing)

-- | Convert spacing atom to PureScript
spacingToPS :: SpacingAtomRec -> Text
spacingToPS s = T.unlines
  [ "-- | spacing-" <> sarName s <> " (" <> T.pack (show (sarPx s)) <> "px)"
  , "-- | UUID5: " <> UUID.toText (sarId s)
  , "spacing" <> sanitizeName (sarName s) <> " :: String"
  , "spacing" <> sanitizeName (sarName s) <> " = \"" <> T.pack (show (sarValue s)) <> "rem\""
  , ""
  ]

-- ===========================================================================
-- Button Molecules
-- ===========================================================================

-- | Generate PureScript module for button molecules
generateButtonMolecule :: Text -> Vector ButtonMoleculeRec -> Text
generateButtonMolecule domain buttons = T.unlines $
  [ "-- | Button molecules for " <> domain
  , "-- | Generated by Foundry Brand Ingestion Engine"
  , "module Brand.Molecules.Button where"
  , ""
  , "import Prelude"
  , "import Halogen.HTML as HH"
  , "import Halogen.HTML.Properties as HP"
  , "import Hydrogen.UI.Core (cls)"
  , ""
  , "-- ============================================================"
  , "-- BUTTON VARIANTS"
  , "-- ============================================================"
  , ""
  ] ++ V.toList (V.map buttonToPS buttons)

-- | Convert button molecule to PureScript component
buttonToPS :: ButtonMoleculeRec -> Text
buttonToPS b = T.unlines
  [ "-- | " <> T.toTitle (bmrVariant b) <> " button"
  , "-- | UUID5: " <> UUID.toText (bmrId b)
  , "-- | Composed from: bg=" <> UUID.toText (bmrBgColor b) <> ", text=" <> UUID.toText (bmrTextColor b)
  , "button" <> T.toTitle (bmrVariant b) <> " :: forall w i. Array (HH.HTML w i) -> HH.HTML w i"
  , "button" <> T.toTitle (bmrVariant b) <> " children ="
  , "  HH.button"
  , "    [ cls"
  , "        [ \"inline-flex items-center justify-center\""
  , "        , \"px-4 py-2\""
  , "        , \"rounded-md\""
  , "        , \"font-medium\""
  , "        , \"transition-colors duration-150\""
  , "        , \"focus:outline-none focus:ring-2 focus:ring-offset-2\""
  , case bmrVariant b of
      "primary" -> "        , \"bg-primary text-white hover:bg-primary/90\""
      "secondary" -> "        , \"bg-white text-primary border border-primary hover:bg-primary/10\""
      _ -> "        , \"bg-gray-100 text-gray-900 hover:bg-gray-200\""
  , "        ]"
  , "    ]"
  , "    children"
  , ""
  ]

-- ===========================================================================
-- Hero Compound
-- ===========================================================================

-- | Generate PureScript module for hero compound
generateHeroCompound :: Text -> Vector HeroCompoundRec -> Text
generateHeroCompound domain heros = T.unlines $
  [ "-- | Hero compounds for " <> domain
  , "-- | Generated by Foundry Brand Ingestion Engine"
  , "module Brand.Compounds.Hero where"
  , ""
  , "import Prelude"
  , "import Halogen.HTML as HH"
  , "import Halogen.HTML.Properties as HP"
  , "import Hydrogen.UI.Core (cls, column, container)"
  , ""
  , "-- ============================================================"
  , "-- HERO SECTIONS"
  , "-- ============================================================"
  , ""
  ] ++ V.toList (V.map heroToPS heros)

-- | Convert hero compound to PureScript component
heroToPS :: HeroCompoundRec -> Text
heroToPS h = T.unlines
  [ "-- | Hero section"
  , "-- | UUID5: " <> UUID.toText (hcrId h)
  , "hero :: forall w i. { heading :: String, subheading :: String, cta :: HH.HTML w i } -> HH.HTML w i"
  , "hero { heading, subheading, cta } ="
  , "  HH.section"
  , "    [ cls [ \"py-24 bg-primary text-white\" ] ]"
  , "    [ container \"\""
  , "        [ column \"gap-6\""
  , "            [ HH.h1"
  , "                [ cls [ \"text-5xl font-heading font-bold\" ] ]"
  , "                [ HH.text heading ]"
  , "            , HH.p"
  , "                [ cls [ \"text-xl font-body opacity-90\" ] ]"
  , "                [ HH.text subheading ]"
  , "            , cta"
  , "            ]"
  , "        ]"
  , "    ]"
  , ""
  ]

-- ===========================================================================
-- Theme (CSS Variables)
-- ===========================================================================

-- | Generate combined theme module with CSS variables
generateTheme :: ExtractedRegistry -> Text
generateTheme reg = T.unlines $
  [ "-- | Brand theme for " <> erDomain reg
  , "-- | Generated by Foundry Brand Ingestion Engine"
  , "module Brand.Theme where"
  , ""
  , "import Prelude"
  , ""
  , "-- ============================================================"
  , "-- CSS CUSTOM PROPERTIES"
  , "-- ============================================================"
  , ""
  , "-- | CSS to inject into document head"
  , "themeCss :: String"
  , "themeCss = \"\"\""
  , ":root {"
  ] <> V.toList (V.map colorToVar (erColors reg))
    <> V.toList (V.map fontToVar (erFonts reg))
    <> V.toList (V.map spacingToVar (erSpacing reg))
    <>
  [ "}"
  , "\"\"\""
  , ""
  , "-- ============================================================"
  , "-- TAILWIND CONFIG (for build integration)"
  , "-- ============================================================"
  , ""
  , "tailwindTheme :: String"
  , "tailwindTheme = \"\"\""
  , "{"
  , "  \"extend\": {"
  , "    \"colors\": {"
  ] <> V.toList (V.imap colorToTailwind (erColors reg))
    <>
  [ "    },"
  , "    \"fontFamily\": {"
  ] <> V.toList (V.imap fontToTailwind (erFonts reg))
    <>
  [ "    }"
  , "  }"
  , "}"
  , "\"\"\""
  ]

colorToVar :: ColorAtomRec -> Text
colorToVar c = "  --color-" <> sanitizeName (carName c) <> ": " <> carHex c <> ";"

fontToVar :: FontAtomRec -> Text
fontToVar f = "  --font-" <> farRole f <> ": \"" <> farFamily f <> "\";"

spacingToVar :: SpacingAtomRec -> Text
spacingToVar s = "  --spacing-" <> sarName s <> ": " <> T.pack (show (sarValue s)) <> "rem;"

colorToTailwind :: Int -> ColorAtomRec -> Text
colorToTailwind i c =
  "      \"" <> sanitizeName (carName c) <> "\": \"" <> carHex c <> "\"" <> comma
  where
    comma = if i < 5 then "," else ""  -- Simplified, would need actual count

fontToTailwind :: Int -> FontAtomRec -> Text
fontToTailwind i f =
  "      \"" <> farRole f <> "\": [\"" <> farFamily f <> "\", \"sans-serif\"]" <> comma
  where
    comma = if i < 2 then "," else ""

-- ===========================================================================
-- Full Generation
-- ===========================================================================

-- | Generate all PureScript modules from extracted registry
generateAll :: ExtractedRegistry -> GeneratedCode
generateAll reg = GeneratedCode
  { gcColors = generateColorAtoms (erDomain reg) (erColors reg)
  , gcTypography = generateFontAtoms (erDomain reg) (erFonts reg)
  , gcSpacing = generateSpacingAtoms (erDomain reg) (erSpacing reg)
  , gcButtons = generateButtonMolecule (erDomain reg) (erButtons reg)
  , gcHero = generateHeroCompound (erDomain reg) (erHeros reg)
  , gcTheme = generateTheme reg
  }

-- ===========================================================================
-- Helpers
-- ===========================================================================

-- | Sanitize name for PureScript identifier
sanitizeName :: Text -> Text
sanitizeName name = T.concatMap sanitizeChar name
  where
    sanitizeChar c
      | c == '-' = "_"
      | c == '.' = "_"
      | c == ' ' = "_"
      | otherwise = T.singleton c
